fix: fix missing control paths issue
Fix regression issue in commit: 5e8aca2756eed71b65ec821c1bf18d10d10fc25b

```
trime/app/src/main/jni/librime/src/rime/switches.cc:117:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
  }
  ^
  1 error generated.
```

We can add more compiler option in CI to avoid issue like this.